packages:
  - "apps/*"
  - "apps/donations/*"

optimisticRepeatInstall: true
strictPeerDependencies: true
dedupePeers: true

peerDependencyRules:
  allowedVersions:
    "next-superjson-plugin>next": "^16.0"
    "react-to-text>react": "^19.0"
    "react-to-text>react-dom": "^19.0"

# FIXME: https://github.com/prettier/prettier/issues/17565
publicHoistPattern:
  - "@trivago/prettier-plugin-sort-imports"
  - "prettier-plugin-tailwindcss"

allowBuilds:
  "@ffmpeg-installer/darwin-arm64": true
  "@ffmpeg-installer/darwin-x64": true
  "@ffmpeg-installer/linux-arm64": true
  "@ffmpeg-installer/linux-arm": true
  "@ffmpeg-installer/linux-ia32": true
  "@ffmpeg-installer/linux-x64": true
  "@ffmpeg-installer/win32-ia32": true
  "@ffmpeg-installer/win32-x64": true
  "@ffprobe-installer/darwin-arm64": true
  "@ffprobe-installer/darwin-x64": true
  "@ffprobe-installer/linux-arm64": true
  "@ffprobe-installer/linux-arm": true
  "@ffprobe-installer/linux-ia32": true
  "@ffprobe-installer/linux-x64": true
  "@ffprobe-installer/win32-ia32": true
  "@ffprobe-installer/win32-x64": true
  "@prisma/engines": true
  "@swc/core": true
  "esbuild": true
  "prisma": true
  "sharp": true
  "unrs-resolver": true
  "workerd": true
