name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: current
    attributes:
      label: What is the current behavior?
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: What is the expected behavior?
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
    validations:
      required: true
  - type: input
    id: browser
    attributes:
      label: Browser specs
      description: Please go to https://www.whatsmybrowser.org/ and copy the link generated into this text area. e.g. https://www.whatsmybrowser.org/b/WTBQ3
    validations:
      required: true
  - type: textarea
    id: notes
    attributes:
      label: Anything else?
      placeholder: If needed, use this to give any further context that might be helpful.
