// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from "./client";
import { client } from "./client.gen";
import type {
  GetConfigCapabilitiesByCameraData,
  GetConfigCapabilitiesByCameraResponses,
  GetConfigSpecsByCameraData,
  GetConfigSpecsByCameraResponses,
  GetInfoPositionData,
  GetInfoPositionResponses,
  GetInfoResolutionData,
  GetInfoResolutionResponses,
  GetInfoScreenshotData,
  GetInfoScreenshotResponses,
  GetInfoSpeedData,
  GetInfoSpeedResponses,
  GetSettingsBrightnessData,
  GetSettingsBrightnessResponses,
  GetSettingsContrastData,
  GetSettingsContrastResponses,
  GetSettingsLocalcontrastData,
  GetSettingsLocalcontrastResponses,
  GetSettingsProportionalspeedData,
  GetSettingsProportionalspeedResponses,
  GetSettingsQuickzoomData,
  GetSettingsQuickzoomResponses,
  GetSettingsSaturationData,
  GetSettingsSaturationResponses,
  GetSettingsSharpnessData,
  GetSettingsSharpnessResponses,
  GetSettingsSpeedData,
  GetSettingsSpeedResponses,
  GetSettingsSpotfocusData,
  GetSettingsSpotfocusResponses,
  GetSettingsTonemappingData,
  GetSettingsTonemappingResponses,
  PostImagingAutofocusData,
  PostImagingAutofocusResponses,
  PostImagingAutoirisData,
  PostImagingAutoirisResponses,
  PostImagingBrightnessData,
  PostImagingBrightnessResponses,
  PostImagingCbrightnessData,
  PostImagingCbrightnessResponses,
  PostImagingCfocusData,
  PostImagingCfocusResponses,
  PostImagingCirisData,
  PostImagingCirisResponses,
  PostImagingFocusData,
  PostImagingFocusResponses,
  PostImagingIrisData,
  PostImagingIrisResponses,
  PostImagingRbrightnessData,
  PostImagingRbrightnessResponses,
  PostImagingRfocusData,
  PostImagingRfocusResponses,
  PostImagingRirisData,
  PostImagingRirisResponses,
  PostIrData,
  PostIrFilterData,
  PostIrFilterResponses,
  PostIrLightData,
  PostIrLightResponses,
  PostIrResponses,
  PostPtzAreazoomData,
  PostPtzAreazoomResponses,
  PostPtzLoadData,
  PostPtzLoadResponses,
  PostPtzMoveData,
  PostPtzMoveResponses,
  PostPtzPanData,
  PostPtzPanResponses,
  PostPtzRpanData,
  PostPtzRpanResponses,
  PostPtzRptzData,
  PostPtzRptzResponses,
  PostPtzRtiltData,
  PostPtzRtiltResponses,
  PostPtzRzoomData,
  PostPtzRzoomResponses,
  PostPtzSpinData,
  PostPtzSpinResponses,
  PostPtzTiltData,
  PostPtzTiltResponses,
  PostPtzZoomData,
  PostPtzZoomResponses,
  PostSettingsBrightnessData,
  PostSettingsBrightnessResponses,
  PostSettingsContrastData,
  PostSettingsContrastResponses,
  PostSettingsLocalcontrastData,
  PostSettingsLocalcontrastResponses,
  PostSettingsProportionalspeedData,
  PostSettingsProportionalspeedResponses,
  PostSettingsQuickzoomData,
  PostSettingsQuickzoomResponses,
  PostSettingsSaturationData,
  PostSettingsSaturationResponses,
  PostSettingsSharpnessData,
  PostSettingsSharpnessResponses,
  PostSettingsSpeedData,
  PostSettingsSpeedResponses,
  PostSettingsSpotfocusData,
  PostSettingsSpotfocusResponses,
  PostSettingsTonemappingData,
  PostSettingsTonemappingResponses,
} from "./types.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * Load
 *
 * Make requests to change the pan, zoom and tilt of a camera
 */
export const postPtzLoad = <ThrowOnError extends boolean = false>(
  options: Options<PostPtzLoadData, ThrowOnError>,
) =>
  (options.client ?? client).post<PostPtzLoadResponses, unknown, ThrowOnError>({
    url: "/ptz/load",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Move
 *
 * Move the camera in a cardinal direction
 */
export const postPtzMove = <ThrowOnError extends boolean = false>(
  options: Options<PostPtzMoveData, ThrowOnError>,
) =>
  (options.client ?? client).post<PostPtzMoveResponses, unknown, ThrowOnError>({
    url: "/ptz/move",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Pan
 *
 * Set absolute pan of the camera
 */
export const postPtzPan = <ThrowOnError extends boolean = false>(
  options: Options<PostPtzPanData, ThrowOnError>,
) =>
  (options.client ?? client).post<PostPtzPanResponses, unknown, ThrowOnError>({
    url: "/ptz/pan",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Tilt
 *
 * Set absolute tilt of the camera
 */
export const postPtzTilt = <ThrowOnError extends boolean = false>(
  options: Options<PostPtzTiltData, ThrowOnError>,
) =>
  (options.client ?? client).post<PostPtzTiltResponses, unknown, ThrowOnError>({
    url: "/ptz/tilt",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Zoom
 *
 * Set absolute zoom of the camera
 */
export const postPtzZoom = <ThrowOnError extends boolean = false>(
  options: Options<PostPtzZoomData, ThrowOnError>,
) =>
  (options.client ?? client).post<PostPtzZoomResponses, unknown, ThrowOnError>({
    url: "/ptz/zoom",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Areazoom
 *
 * Zoom to an area defined by x, y, and z
 */
export const postPtzAreazoom = <ThrowOnError extends boolean = false>(
  options: Options<PostPtzAreazoomData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    PostPtzAreazoomResponses,
    unknown,
    ThrowOnError
  >({
    url: "/ptz/areazoom",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Spin
 *
 * Set continuous pan, tilt, and zoom movement
 */
export const postPtzSpin = <ThrowOnError extends boolean = false>(
  options: Options<PostPtzSpinData, ThrowOnError>,
) =>
  (options.client ?? client).post<PostPtzSpinResponses, unknown, ThrowOnError>({
    url: "/ptz/spin",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Relative PTZ
 *
 * Set relative pan, tilt, and zoom values
 */
export const postPtzRptz = <ThrowOnError extends boolean = false>(
  options: Options<PostPtzRptzData, ThrowOnError>,
) =>
  (options.client ?? client).post<PostPtzRptzResponses, unknown, ThrowOnError>({
    url: "/ptz/rptz",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Relative Pan
 *
 * Set relative pan movement of the camera
 */
export const postPtzRpan = <ThrowOnError extends boolean = false>(
  options: Options<PostPtzRpanData, ThrowOnError>,
) =>
  (options.client ?? client).post<PostPtzRpanResponses, unknown, ThrowOnError>({
    url: "/ptz/rpan",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Relative Tilt
 *
 * Set relative tilt movement of the camera
 */
export const postPtzRtilt = <ThrowOnError extends boolean = false>(
  options: Options<PostPtzRtiltData, ThrowOnError>,
) =>
  (options.client ?? client).post<PostPtzRtiltResponses, unknown, ThrowOnError>(
    {
      url: "/ptz/rtilt",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    },
  );

/**
 * Relative Zoom
 *
 * Set relative zoom movement of the camera
 */
export const postPtzRzoom = <ThrowOnError extends boolean = false>(
  options: Options<PostPtzRzoomData, ThrowOnError>,
) =>
  (options.client ?? client).post<PostPtzRzoomResponses, unknown, ThrowOnError>(
    {
      url: "/ptz/rzoom",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    },
  );

/**
 * IR
 *
 * Set IR filter and light state together
 */
export const postIr = <ThrowOnError extends boolean = false>(
  options: Options<PostIrData, ThrowOnError>,
) =>
  (options.client ?? client).post<PostIrResponses, unknown, ThrowOnError>({
    url: "/ir",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * IR Filter
 *
 * Set IR cut filter state
 */
export const postIrFilter = <ThrowOnError extends boolean = false>(
  options: Options<PostIrFilterData, ThrowOnError>,
) =>
  (options.client ?? client).post<PostIrFilterResponses, unknown, ThrowOnError>(
    {
      url: "/ir/filter",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    },
  );

/**
 * IR Light
 *
 * Set IR light state
 */
export const postIrLight = <ThrowOnError extends boolean = false>(
  options: Options<PostIrLightData, ThrowOnError>,
) =>
  (options.client ?? client).post<PostIrLightResponses, unknown, ThrowOnError>({
    url: "/ir/light",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get Info
 *
 * Get information about a specific camera
 */
export const getInfoPosition = <ThrowOnError extends boolean = false>(
  options: Options<GetInfoPositionData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetInfoPositionResponses,
    unknown,
    ThrowOnError
  >({ url: "/info/position", ...options });

/**
 * Get Speed
 *
 * Get the speed of the camera
 */
export const getInfoSpeed = <ThrowOnError extends boolean = false>(
  options: Options<GetInfoSpeedData, ThrowOnError>,
) =>
  (options.client ?? client).get<GetInfoSpeedResponses, unknown, ThrowOnError>({
    url: "/info/speed",
    ...options,
  });

/**
 * Get Screenshot
 *
 * Get a screenshot of the current view of the camera
 */
export const getInfoScreenshot = <ThrowOnError extends boolean = false>(
  options: Options<GetInfoScreenshotData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetInfoScreenshotResponses,
    unknown,
    ThrowOnError
  >({ url: "/info/screenshot", ...options });

/**
 * Get Resolution
 *
 * Get the camera's output resolution
 */
export const getInfoResolution = <ThrowOnError extends boolean = false>(
  options: Options<GetInfoResolutionData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetInfoResolutionResponses,
    unknown,
    ThrowOnError
  >({ url: "/info/resolution", ...options });

/**
 * Focus
 *
 * Set absolute focus level
 */
export const postImagingFocus = <ThrowOnError extends boolean = false>(
  options: Options<PostImagingFocusData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    PostImagingFocusResponses,
    unknown,
    ThrowOnError
  >({
    url: "/imaging/focus",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Brightness
 *
 * Set absolute brightness level
 */
export const postImagingBrightness = <ThrowOnError extends boolean = false>(
  options: Options<PostImagingBrightnessData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    PostImagingBrightnessResponses,
    unknown,
    ThrowOnError
  >({
    url: "/imaging/brightness",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Iris
 *
 * Set absolute iris level
 */
export const postImagingIris = <ThrowOnError extends boolean = false>(
  options: Options<PostImagingIrisData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    PostImagingIrisResponses,
    unknown,
    ThrowOnError
  >({
    url: "/imaging/iris",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Relative Focus
 *
 * Set relative focus movement
 */
export const postImagingRfocus = <ThrowOnError extends boolean = false>(
  options: Options<PostImagingRfocusData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    PostImagingRfocusResponses,
    unknown,
    ThrowOnError
  >({
    url: "/imaging/rfocus",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Relative Brightness
 *
 * Set relative brightness movement
 */
export const postImagingRbrightness = <ThrowOnError extends boolean = false>(
  options: Options<PostImagingRbrightnessData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    PostImagingRbrightnessResponses,
    unknown,
    ThrowOnError
  >({
    url: "/imaging/rbrightness",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Relative Iris
 *
 * Set relative iris movement
 */
export const postImagingRiris = <ThrowOnError extends boolean = false>(
  options: Options<PostImagingRirisData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    PostImagingRirisResponses,
    unknown,
    ThrowOnError
  >({
    url: "/imaging/riris",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Autofocus
 *
 * Set autofocus mode
 */
export const postImagingAutofocus = <ThrowOnError extends boolean = false>(
  options: Options<PostImagingAutofocusData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    PostImagingAutofocusResponses,
    unknown,
    ThrowOnError
  >({
    url: "/imaging/autofocus",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Auto Iris
 *
 * Set auto iris mode
 */
export const postImagingAutoiris = <ThrowOnError extends boolean = false>(
  options: Options<PostImagingAutoirisData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    PostImagingAutoirisResponses,
    unknown,
    ThrowOnError
  >({
    url: "/imaging/autoiris",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Continuous Focus
 *
 * Set continuous focus movement
 */
export const postImagingCfocus = <ThrowOnError extends boolean = false>(
  options: Options<PostImagingCfocusData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    PostImagingCfocusResponses,
    unknown,
    ThrowOnError
  >({
    url: "/imaging/cfocus",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Continuous Brightness
 *
 * Set continuous brightness movement
 */
export const postImagingCbrightness = <ThrowOnError extends boolean = false>(
  options: Options<PostImagingCbrightnessData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    PostImagingCbrightnessResponses,
    unknown,
    ThrowOnError
  >({
    url: "/imaging/cbrightness",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Continuous Iris
 *
 * Set continuous iris movement
 */
export const postImagingCiris = <ThrowOnError extends boolean = false>(
  options: Options<PostImagingCirisData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    PostImagingCirisResponses,
    unknown,
    ThrowOnError
  >({
    url: "/imaging/ciris",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get a camera parameter
 */
export const getSettingsQuickzoom = <ThrowOnError extends boolean = false>(
  options: Options<GetSettingsQuickzoomData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetSettingsQuickzoomResponses,
    unknown,
    ThrowOnError
  >({ url: "/settings/quickzoom", ...options });

/**
 * Set a boolean camera parameter
 */
export const postSettingsQuickzoom = <ThrowOnError extends boolean = false>(
  options: Options<PostSettingsQuickzoomData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    PostSettingsQuickzoomResponses,
    unknown,
    ThrowOnError
  >({
    url: "/settings/quickzoom",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get a camera parameter
 */
export const getSettingsSpotfocus = <ThrowOnError extends boolean = false>(
  options: Options<GetSettingsSpotfocusData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetSettingsSpotfocusResponses,
    unknown,
    ThrowOnError
  >({ url: "/settings/spotfocus", ...options });

/**
 * Set a boolean camera parameter
 */
export const postSettingsSpotfocus = <ThrowOnError extends boolean = false>(
  options: Options<PostSettingsSpotfocusData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    PostSettingsSpotfocusResponses,
    unknown,
    ThrowOnError
  >({
    url: "/settings/spotfocus",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get a camera parameter
 */
export const getSettingsSaturation = <ThrowOnError extends boolean = false>(
  options: Options<GetSettingsSaturationData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetSettingsSaturationResponses,
    unknown,
    ThrowOnError
  >({ url: "/settings/saturation", ...options });

/**
 * Set an integer camera parameter
 */
export const postSettingsSaturation = <ThrowOnError extends boolean = false>(
  options: Options<PostSettingsSaturationData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    PostSettingsSaturationResponses,
    unknown,
    ThrowOnError
  >({
    url: "/settings/saturation",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get a camera parameter
 */
export const getSettingsBrightness = <ThrowOnError extends boolean = false>(
  options: Options<GetSettingsBrightnessData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetSettingsBrightnessResponses,
    unknown,
    ThrowOnError
  >({ url: "/settings/brightness", ...options });

/**
 * Set an integer camera parameter
 */
export const postSettingsBrightness = <ThrowOnError extends boolean = false>(
  options: Options<PostSettingsBrightnessData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    PostSettingsBrightnessResponses,
    unknown,
    ThrowOnError
  >({
    url: "/settings/brightness",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get a camera parameter
 */
export const getSettingsContrast = <ThrowOnError extends boolean = false>(
  options: Options<GetSettingsContrastData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetSettingsContrastResponses,
    unknown,
    ThrowOnError
  >({ url: "/settings/contrast", ...options });

/**
 * Set an integer camera parameter
 */
export const postSettingsContrast = <ThrowOnError extends boolean = false>(
  options: Options<PostSettingsContrastData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    PostSettingsContrastResponses,
    unknown,
    ThrowOnError
  >({
    url: "/settings/contrast",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get a camera parameter
 */
export const getSettingsSharpness = <ThrowOnError extends boolean = false>(
  options: Options<GetSettingsSharpnessData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetSettingsSharpnessResponses,
    unknown,
    ThrowOnError
  >({ url: "/settings/sharpness", ...options });

/**
 * Set an integer camera parameter
 */
export const postSettingsSharpness = <ThrowOnError extends boolean = false>(
  options: Options<PostSettingsSharpnessData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    PostSettingsSharpnessResponses,
    unknown,
    ThrowOnError
  >({
    url: "/settings/sharpness",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get a camera parameter
 */
export const getSettingsLocalcontrast = <ThrowOnError extends boolean = false>(
  options: Options<GetSettingsLocalcontrastData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetSettingsLocalcontrastResponses,
    unknown,
    ThrowOnError
  >({ url: "/settings/localcontrast", ...options });

/**
 * Set an integer camera parameter
 */
export const postSettingsLocalcontrast = <ThrowOnError extends boolean = false>(
  options: Options<PostSettingsLocalcontrastData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    PostSettingsLocalcontrastResponses,
    unknown,
    ThrowOnError
  >({
    url: "/settings/localcontrast",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get a camera parameter
 */
export const getSettingsTonemapping = <ThrowOnError extends boolean = false>(
  options: Options<GetSettingsTonemappingData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetSettingsTonemappingResponses,
    unknown,
    ThrowOnError
  >({ url: "/settings/tonemapping", ...options });

/**
 * Set an integer camera parameter
 */
export const postSettingsTonemapping = <ThrowOnError extends boolean = false>(
  options: Options<PostSettingsTonemappingData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    PostSettingsTonemappingResponses,
    unknown,
    ThrowOnError
  >({
    url: "/settings/tonemapping",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get a camera parameter
 */
export const getSettingsProportionalspeed = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetSettingsProportionalspeedData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetSettingsProportionalspeedResponses,
    unknown,
    ThrowOnError
  >({ url: "/settings/proportionalspeed", ...options });

/**
 * Set an integer camera parameter
 */
export const postSettingsProportionalspeed = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PostSettingsProportionalspeedData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    PostSettingsProportionalspeedResponses,
    unknown,
    ThrowOnError
  >({
    url: "/settings/proportionalspeed",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get Speed
 *
 * Get the speed of the camera
 */
export const getSettingsSpeed = <ThrowOnError extends boolean = false>(
  options: Options<GetSettingsSpeedData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetSettingsSpeedResponses,
    unknown,
    ThrowOnError
  >({ url: "/settings/speed", ...options });

/**
 * Set Speed
 *
 * Set camera speed and return updated speed
 */
export const postSettingsSpeed = <ThrowOnError extends boolean = false>(
  options: Options<PostSettingsSpeedData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    PostSettingsSpeedResponses,
    unknown,
    ThrowOnError
  >({
    url: "/settings/speed",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get Capabilities
 *
 * Get capabilities for a specific camera
 */
export const getConfigCapabilitiesByCamera = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetConfigCapabilitiesByCameraData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetConfigCapabilitiesByCameraResponses,
    unknown,
    ThrowOnError
  >({ url: "/config/capabilities/{camera}", ...options });

/**
 * Get Specs
 *
 * Get specifications for a specific camera
 */
export const getConfigSpecsByCamera = <ThrowOnError extends boolean = false>(
  options: Options<GetConfigSpecsByCameraData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetConfigSpecsByCameraResponses,
    unknown,
    ThrowOnError
  >({ url: "/config/specs/{camera}", ...options });
