// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: "http://localhost:1229" | (string & {});
};

export type PostPtzLoadData = {
  body: {
    pan?: number & number;
    tilt?: number & number;
    zoom?: number & number;
    focus?: number & number;
  };
  headers: {
    "x-camera-name": string;
  };
  path?: never;
  query?: never;
  url: "/ptz/load";
};

export type PostPtzLoadResponses = {
  /**
   * Successfully submitted to the camera
   */
  200: string;
};

export type PostPtzLoadResponse =
  PostPtzLoadResponses[keyof PostPtzLoadResponses];

export type PostPtzMoveData = {
  body: {
    direction:
      | "upleft"
      | "up"
      | "upright"
      | "left"
      | "home"
      | "right"
      | "downleft"
      | "down"
      | "downright"
      | "stop";
  };
  headers: {
    "x-camera-name": string;
  };
  path?: never;
  query?: never;
  url: "/ptz/move";
};

export type PostPtzMoveResponses = {
  /**
   * Successfully submitted to the camera
   */
  200: string;
};

export type PostPtzMoveResponse =
  PostPtzMoveResponses[keyof PostPtzMoveResponses];

export type PostPtzPanData = {
  body: {
    degrees: number & number;
  };
  headers: {
    "x-camera-name": string;
  };
  path?: never;
  query?: never;
  url: "/ptz/pan";
};

export type PostPtzPanResponses = {
  /**
   * Successfully submitted to the camera
   */
  200: string;
};

export type PostPtzPanResponse = PostPtzPanResponses[keyof PostPtzPanResponses];

export type PostPtzTiltData = {
  body: {
    degrees: number & number;
  };
  headers: {
    "x-camera-name": string;
  };
  path?: never;
  query?: never;
  url: "/ptz/tilt";
};

export type PostPtzTiltResponses = {
  /**
   * Successfully submitted to the camera
   */
  200: string;
};

export type PostPtzTiltResponse =
  PostPtzTiltResponses[keyof PostPtzTiltResponses];

export type PostPtzZoomData = {
  body: {
    value: number & number;
  };
  headers: {
    "x-camera-name": string;
  };
  path?: never;
  query?: never;
  url: "/ptz/zoom";
};

export type PostPtzZoomResponses = {
  /**
   * Successfully submitted to the camera
   */
  200: string;
};

export type PostPtzZoomResponse =
  PostPtzZoomResponses[keyof PostPtzZoomResponses];

export type PostPtzAreazoomData = {
  body: {
    x: number;
    y: number;
    z: number;
  };
  headers: {
    "x-camera-name": string;
  };
  path?: never;
  query?: never;
  url: "/ptz/areazoom";
};

export type PostPtzAreazoomResponses = {
  /**
   * Successfully submitted to the camera
   */
  200: string;
};

export type PostPtzAreazoomResponse =
  PostPtzAreazoomResponses[keyof PostPtzAreazoomResponses];

export type PostPtzSpinData = {
  body: {
    pan: number & number;
    tilt: number & number;
    zoom: number & number;
  };
  headers: {
    "x-camera-name": string;
  };
  path?: never;
  query?: never;
  url: "/ptz/spin";
};

export type PostPtzSpinResponses = {
  /**
   * Successfully submitted to the camera
   */
  200: string;
};

export type PostPtzSpinResponse =
  PostPtzSpinResponses[keyof PostPtzSpinResponses];

export type PostPtzRptzData = {
  body: {
    pan?: number & number;
    tilt?: number & number;
    zoom?: number & number;
  };
  headers: {
    "x-camera-name": string;
  };
  path?: never;
  query?: never;
  url: "/ptz/rptz";
};

export type PostPtzRptzResponses = {
  /**
   * Successfully submitted to the camera
   */
  200: string;
};

export type PostPtzRptzResponse =
  PostPtzRptzResponses[keyof PostPtzRptzResponses];

export type PostPtzRpanData = {
  body: {
    degrees: number & number;
  };
  headers: {
    "x-camera-name": string;
  };
  path?: never;
  query?: never;
  url: "/ptz/rpan";
};

export type PostPtzRpanResponses = {
  /**
   * Successfully submitted to the camera
   */
  200: string;
};

export type PostPtzRpanResponse =
  PostPtzRpanResponses[keyof PostPtzRpanResponses];

export type PostPtzRtiltData = {
  body: {
    degrees: number & number;
  };
  headers: {
    "x-camera-name": string;
  };
  path?: never;
  query?: never;
  url: "/ptz/rtilt";
};

export type PostPtzRtiltResponses = {
  /**
   * Successfully submitted to the camera
   */
  200: string;
};

export type PostPtzRtiltResponse =
  PostPtzRtiltResponses[keyof PostPtzRtiltResponses];

export type PostPtzRzoomData = {
  body: {
    value: number & number;
  };
  headers: {
    "x-camera-name": string;
  };
  path?: never;
  query?: never;
  url: "/ptz/rzoom";
};

export type PostPtzRzoomResponses = {
  /**
   * Successfully submitted to the camera
   */
  200: string;
};

export type PostPtzRzoomResponse =
  PostPtzRzoomResponses[keyof PostPtzRzoomResponses];

export type PostIrData = {
  body: {
    light: string;
    state: "on" | "off" | "auto";
  };
  headers: {
    "x-camera-name": string;
  };
  path?: never;
  query?: never;
  url: "/ir";
};

export type PostIrResponses = {
  /**
   * Successfully submitted to the camera
   */
  200: string;
};

export type PostIrResponse = PostIrResponses[keyof PostIrResponses];

export type PostIrFilterData = {
  body: {
    state: "on" | "off" | "auto";
  };
  headers: {
    "x-camera-name": string;
  };
  path?: never;
  query?: never;
  url: "/ir/filter";
};

export type PostIrFilterResponses = {
  /**
   * Successfully submitted to the camera
   */
  200: string;
};

export type PostIrFilterResponse =
  PostIrFilterResponses[keyof PostIrFilterResponses];

export type PostIrLightData = {
  body: {
    light: string;
    state: "on" | "off";
  };
  headers: {
    "x-camera-name": string;
  };
  path?: never;
  query?: never;
  url: "/ir/light";
};

export type PostIrLightResponses = {
  /**
   * Successfully submitted to the camera
   */
  200: string;
};

export type PostIrLightResponse =
  PostIrLightResponses[keyof PostIrLightResponses];

export type GetInfoPositionData = {
  body?: never;
  headers: {
    "x-camera-name": string;
  };
  path?: never;
  query?: never;
  url: "/info/position";
};

export type GetInfoPositionResponses = {
  /**
   * Information about a camera
   */
  200: {
    [key: string]: number | string;
  };
};

export type GetInfoPositionResponse =
  GetInfoPositionResponses[keyof GetInfoPositionResponses];

export type GetInfoSpeedData = {
  body?: never;
  headers: {
    "x-camera-name": string;
  };
  path?: never;
  query?: never;
  url: "/info/speed";
};

export type GetInfoSpeedResponses = {
  /**
   * Speed of the camera
   */
  200: {
    [key: string]: number | string;
  };
};

export type GetInfoSpeedResponse =
  GetInfoSpeedResponses[keyof GetInfoSpeedResponses];

export type GetInfoScreenshotData = {
  body?: never;
  headers: {
    "x-camera-name": string;
  };
  path?: never;
  query?: {
    width?: number;
    height?: number;
  };
  url: "/info/screenshot";
};

export type GetInfoScreenshotResponses = {
  /**
   * Base64 encoded image
   */
  200: string;
};

export type GetInfoScreenshotResponse =
  GetInfoScreenshotResponses[keyof GetInfoScreenshotResponses];

export type GetInfoResolutionData = {
  body?: never;
  headers: {
    "x-camera-name": string;
  };
  path?: never;
  query?: never;
  url: "/info/resolution";
};

export type GetInfoResolutionResponses = {
  /**
   * Current resolution
   */
  200: {
    [key: string]: number | string;
  };
};

export type GetInfoResolutionResponse =
  GetInfoResolutionResponses[keyof GetInfoResolutionResponses];

export type PostImagingFocusData = {
  body: {
    value: number & number;
  };
  headers: {
    "x-camera-name": string;
  };
  path?: never;
  query?: never;
  url: "/imaging/focus";
};

export type PostImagingFocusResponses = {
  /**
   * Successfully submitted to the camera
   */
  200: string;
};

export type PostImagingFocusResponse =
  PostImagingFocusResponses[keyof PostImagingFocusResponses];

export type PostImagingBrightnessData = {
  body: {
    value: number & number;
  };
  headers: {
    "x-camera-name": string;
  };
  path?: never;
  query?: never;
  url: "/imaging/brightness";
};

export type PostImagingBrightnessResponses = {
  /**
   * Successfully submitted to the camera
   */
  200: string;
};

export type PostImagingBrightnessResponse =
  PostImagingBrightnessResponses[keyof PostImagingBrightnessResponses];

export type PostImagingIrisData = {
  body: {
    value: number & number;
  };
  headers: {
    "x-camera-name": string;
  };
  path?: never;
  query?: never;
  url: "/imaging/iris";
};

export type PostImagingIrisResponses = {
  /**
   * Successfully submitted to the camera
   */
  200: string;
};

export type PostImagingIrisResponse =
  PostImagingIrisResponses[keyof PostImagingIrisResponses];

export type PostImagingRfocusData = {
  body: {
    value: number & number;
  };
  headers: {
    "x-camera-name": string;
  };
  path?: never;
  query?: never;
  url: "/imaging/rfocus";
};

export type PostImagingRfocusResponses = {
  /**
   * Successfully submitted to the camera
   */
  200: string;
};

export type PostImagingRfocusResponse =
  PostImagingRfocusResponses[keyof PostImagingRfocusResponses];

export type PostImagingRbrightnessData = {
  body: {
    value: number & number;
  };
  headers: {
    "x-camera-name": string;
  };
  path?: never;
  query?: never;
  url: "/imaging/rbrightness";
};

export type PostImagingRbrightnessResponses = {
  /**
   * Successfully submitted to the camera
   */
  200: string;
};

export type PostImagingRbrightnessResponse =
  PostImagingRbrightnessResponses[keyof PostImagingRbrightnessResponses];

export type PostImagingRirisData = {
  body: {
    value: number & number;
  };
  headers: {
    "x-camera-name": string;
  };
  path?: never;
  query?: never;
  url: "/imaging/riris";
};

export type PostImagingRirisResponses = {
  /**
   * Successfully submitted to the camera
   */
  200: string;
};

export type PostImagingRirisResponse =
  PostImagingRirisResponses[keyof PostImagingRirisResponses];

export type PostImagingAutofocusData = {
  body: {
    state: "on" | "off";
  };
  headers: {
    "x-camera-name": string;
  };
  path?: never;
  query?: never;
  url: "/imaging/autofocus";
};

export type PostImagingAutofocusResponses = {
  /**
   * Successfully submitted to the camera
   */
  200: string;
};

export type PostImagingAutofocusResponse =
  PostImagingAutofocusResponses[keyof PostImagingAutofocusResponses];

export type PostImagingAutoirisData = {
  body: {
    state: "on" | "off";
  };
  headers: {
    "x-camera-name": string;
  };
  path?: never;
  query?: never;
  url: "/imaging/autoiris";
};

export type PostImagingAutoirisResponses = {
  /**
   * Successfully submitted to the camera
   */
  200: string;
};

export type PostImagingAutoirisResponse =
  PostImagingAutoirisResponses[keyof PostImagingAutoirisResponses];

export type PostImagingCfocusData = {
  body: {
    value: number & number;
  };
  headers: {
    "x-camera-name": string;
  };
  path?: never;
  query?: never;
  url: "/imaging/cfocus";
};

export type PostImagingCfocusResponses = {
  /**
   * Successfully submitted to the camera
   */
  200: string;
};

export type PostImagingCfocusResponse =
  PostImagingCfocusResponses[keyof PostImagingCfocusResponses];

export type PostImagingCbrightnessData = {
  body: {
    value: number & number;
  };
  headers: {
    "x-camera-name": string;
  };
  path?: never;
  query?: never;
  url: "/imaging/cbrightness";
};

export type PostImagingCbrightnessResponses = {
  /**
   * Successfully submitted to the camera
   */
  200: string;
};

export type PostImagingCbrightnessResponse =
  PostImagingCbrightnessResponses[keyof PostImagingCbrightnessResponses];

export type PostImagingCirisData = {
  body: {
    value: number & number;
  };
  headers: {
    "x-camera-name": string;
  };
  path?: never;
  query?: never;
  url: "/imaging/ciris";
};

export type PostImagingCirisResponses = {
  /**
   * Successfully submitted to the camera
   */
  200: string;
};

export type PostImagingCirisResponse =
  PostImagingCirisResponses[keyof PostImagingCirisResponses];

export type GetSettingsQuickzoomData = {
  body?: never;
  headers: {
    "x-camera-name": string;
  };
  path?: never;
  query?: never;
  url: "/settings/quickzoom";
};

export type GetSettingsQuickzoomResponses = {
  /**
   * Parameter state
   */
  200: {
    [key: string]: unknown;
  };
};

export type GetSettingsQuickzoomResponse =
  GetSettingsQuickzoomResponses[keyof GetSettingsQuickzoomResponses];

export type PostSettingsQuickzoomData = {
  body: {
    enabled: boolean;
  };
  headers: {
    "x-camera-name": string;
  };
  path?: never;
  query?: never;
  url: "/settings/quickzoom";
};

export type PostSettingsQuickzoomResponses = {
  /**
   * Parameter state
   */
  200: {
    [key: string]: unknown;
  };
};

export type PostSettingsQuickzoomResponse =
  PostSettingsQuickzoomResponses[keyof PostSettingsQuickzoomResponses];

export type GetSettingsSpotfocusData = {
  body?: never;
  headers: {
    "x-camera-name": string;
  };
  path?: never;
  query?: never;
  url: "/settings/spotfocus";
};

export type GetSettingsSpotfocusResponses = {
  /**
   * Parameter state
   */
  200: {
    [key: string]: unknown;
  };
};

export type GetSettingsSpotfocusResponse =
  GetSettingsSpotfocusResponses[keyof GetSettingsSpotfocusResponses];

export type PostSettingsSpotfocusData = {
  body: {
    enabled: boolean;
  };
  headers: {
    "x-camera-name": string;
  };
  path?: never;
  query?: never;
  url: "/settings/spotfocus";
};

export type PostSettingsSpotfocusResponses = {
  /**
   * Parameter state
   */
  200: {
    [key: string]: unknown;
  };
};

export type PostSettingsSpotfocusResponse =
  PostSettingsSpotfocusResponses[keyof PostSettingsSpotfocusResponses];

export type GetSettingsSaturationData = {
  body?: never;
  headers: {
    "x-camera-name": string;
  };
  path?: never;
  query?: never;
  url: "/settings/saturation";
};

export type GetSettingsSaturationResponses = {
  /**
   * Parameter state
   */
  200: {
    [key: string]: unknown;
  };
};

export type GetSettingsSaturationResponse =
  GetSettingsSaturationResponses[keyof GetSettingsSaturationResponses];

export type PostSettingsSaturationData = {
  body: {
    value: number & number;
  };
  headers: {
    "x-camera-name": string;
  };
  path?: never;
  query?: never;
  url: "/settings/saturation";
};

export type PostSettingsSaturationResponses = {
  /**
   * Parameter state
   */
  200: {
    [key: string]: unknown;
  };
};

export type PostSettingsSaturationResponse =
  PostSettingsSaturationResponses[keyof PostSettingsSaturationResponses];

export type GetSettingsBrightnessData = {
  body?: never;
  headers: {
    "x-camera-name": string;
  };
  path?: never;
  query?: never;
  url: "/settings/brightness";
};

export type GetSettingsBrightnessResponses = {
  /**
   * Parameter state
   */
  200: {
    [key: string]: unknown;
  };
};

export type GetSettingsBrightnessResponse =
  GetSettingsBrightnessResponses[keyof GetSettingsBrightnessResponses];

export type PostSettingsBrightnessData = {
  body: {
    value: number & number;
  };
  headers: {
    "x-camera-name": string;
  };
  path?: never;
  query?: never;
  url: "/settings/brightness";
};

export type PostSettingsBrightnessResponses = {
  /**
   * Parameter state
   */
  200: {
    [key: string]: unknown;
  };
};

export type PostSettingsBrightnessResponse =
  PostSettingsBrightnessResponses[keyof PostSettingsBrightnessResponses];

export type GetSettingsContrastData = {
  body?: never;
  headers: {
    "x-camera-name": string;
  };
  path?: never;
  query?: never;
  url: "/settings/contrast";
};

export type GetSettingsContrastResponses = {
  /**
   * Parameter state
   */
  200: {
    [key: string]: unknown;
  };
};

export type GetSettingsContrastResponse =
  GetSettingsContrastResponses[keyof GetSettingsContrastResponses];

export type PostSettingsContrastData = {
  body: {
    value: number & number;
  };
  headers: {
    "x-camera-name": string;
  };
  path?: never;
  query?: never;
  url: "/settings/contrast";
};

export type PostSettingsContrastResponses = {
  /**
   * Parameter state
   */
  200: {
    [key: string]: unknown;
  };
};

export type PostSettingsContrastResponse =
  PostSettingsContrastResponses[keyof PostSettingsContrastResponses];

export type GetSettingsSharpnessData = {
  body?: never;
  headers: {
    "x-camera-name": string;
  };
  path?: never;
  query?: never;
  url: "/settings/sharpness";
};

export type GetSettingsSharpnessResponses = {
  /**
   * Parameter state
   */
  200: {
    [key: string]: unknown;
  };
};

export type GetSettingsSharpnessResponse =
  GetSettingsSharpnessResponses[keyof GetSettingsSharpnessResponses];

export type PostSettingsSharpnessData = {
  body: {
    value: number & number;
  };
  headers: {
    "x-camera-name": string;
  };
  path?: never;
  query?: never;
  url: "/settings/sharpness";
};

export type PostSettingsSharpnessResponses = {
  /**
   * Parameter state
   */
  200: {
    [key: string]: unknown;
  };
};

export type PostSettingsSharpnessResponse =
  PostSettingsSharpnessResponses[keyof PostSettingsSharpnessResponses];

export type GetSettingsLocalcontrastData = {
  body?: never;
  headers: {
    "x-camera-name": string;
  };
  path?: never;
  query?: never;
  url: "/settings/localcontrast";
};

export type GetSettingsLocalcontrastResponses = {
  /**
   * Parameter state
   */
  200: {
    [key: string]: unknown;
  };
};

export type GetSettingsLocalcontrastResponse =
  GetSettingsLocalcontrastResponses[keyof GetSettingsLocalcontrastResponses];

export type PostSettingsLocalcontrastData = {
  body: {
    value: number & number;
  };
  headers: {
    "x-camera-name": string;
  };
  path?: never;
  query?: never;
  url: "/settings/localcontrast";
};

export type PostSettingsLocalcontrastResponses = {
  /**
   * Parameter state
   */
  200: {
    [key: string]: unknown;
  };
};

export type PostSettingsLocalcontrastResponse =
  PostSettingsLocalcontrastResponses[keyof PostSettingsLocalcontrastResponses];

export type GetSettingsTonemappingData = {
  body?: never;
  headers: {
    "x-camera-name": string;
  };
  path?: never;
  query?: never;
  url: "/settings/tonemapping";
};

export type GetSettingsTonemappingResponses = {
  /**
   * Parameter state
   */
  200: {
    [key: string]: unknown;
  };
};

export type GetSettingsTonemappingResponse =
  GetSettingsTonemappingResponses[keyof GetSettingsTonemappingResponses];

export type PostSettingsTonemappingData = {
  body: {
    value: number & number;
  };
  headers: {
    "x-camera-name": string;
  };
  path?: never;
  query?: never;
  url: "/settings/tonemapping";
};

export type PostSettingsTonemappingResponses = {
  /**
   * Parameter state
   */
  200: {
    [key: string]: unknown;
  };
};

export type PostSettingsTonemappingResponse =
  PostSettingsTonemappingResponses[keyof PostSettingsTonemappingResponses];

export type GetSettingsProportionalspeedData = {
  body?: never;
  headers: {
    "x-camera-name": string;
  };
  path?: never;
  query?: never;
  url: "/settings/proportionalspeed";
};

export type GetSettingsProportionalspeedResponses = {
  /**
   * Parameter state
   */
  200: {
    [key: string]: unknown;
  };
};

export type GetSettingsProportionalspeedResponse =
  GetSettingsProportionalspeedResponses[keyof GetSettingsProportionalspeedResponses];

export type PostSettingsProportionalspeedData = {
  body: {
    value: number & number;
  };
  headers: {
    "x-camera-name": string;
  };
  path?: never;
  query?: never;
  url: "/settings/proportionalspeed";
};

export type PostSettingsProportionalspeedResponses = {
  /**
   * Parameter state
   */
  200: {
    [key: string]: unknown;
  };
};

export type PostSettingsProportionalspeedResponse =
  PostSettingsProportionalspeedResponses[keyof PostSettingsProportionalspeedResponses];

export type GetSettingsSpeedData = {
  body?: never;
  headers: {
    "x-camera-name": string;
  };
  path?: never;
  query?: never;
  url: "/settings/speed";
};

export type GetSettingsSpeedResponses = {
  /**
   * Speed of the camera
   */
  200: {
    [key: string]: number | string;
  };
};

export type GetSettingsSpeedResponse =
  GetSettingsSpeedResponses[keyof GetSettingsSpeedResponses];

export type PostSettingsSpeedData = {
  body: {
    value: number & number;
  };
  headers: {
    "x-camera-name": string;
  };
  path?: never;
  query?: never;
  url: "/settings/speed";
};

export type PostSettingsSpeedResponses = {
  /**
   * Updated camera speed
   */
  200: {
    [key: string]: number | string;
  };
};

export type PostSettingsSpeedResponse =
  PostSettingsSpeedResponses[keyof PostSettingsSpeedResponses];

export type GetConfigCapabilitiesByCameraData = {
  body?: never;
  path: {
    camera: string;
  };
  query?: never;
  url: "/config/capabilities/{camera}";
};

export type GetConfigCapabilitiesByCameraResponses = {
  /**
   * Camera capabilities
   */
  200: {
    camera: string;
    capabilities: Array<string>;
  };
};

export type GetConfigCapabilitiesByCameraResponse =
  GetConfigCapabilitiesByCameraResponses[keyof GetConfigCapabilitiesByCameraResponses];

export type GetConfigSpecsByCameraData = {
  body?: never;
  path: {
    camera: string;
  };
  query?: never;
  url: "/config/specs/{camera}";
};

export type GetConfigSpecsByCameraResponses = {
  /**
   * Camera specs
   */
  200: {
    camera: string;
    specs: {
      [key: string]: unknown;
    };
  };
};

export type GetConfigSpecsByCameraResponse =
  GetConfigSpecsByCameraResponses[keyof GetConfigSpecsByCameraResponses];
