// This file is auto-generated by @hey-api/openapi-ts

import * as z from "zod";

export const PtzLoadBodySchema = z.object({
  pan: z.intersection(z.number().gte(-180), z.number().lte(180)).optional(),
  tilt: z.intersection(z.number().gte(-180), z.number().lte(180)).optional(),
  zoom: z.intersection(z.number().gte(1), z.number().lte(19999)).optional(),
  focus: z.intersection(z.number().gte(1), z.number().lte(19999)).optional(),
});

export const zPostPtzLoadHeaders = z.object({
  "x-camera-name": z.string().min(1).max(100),
});

/**
 * Successfully submitted to the camera
 */
export const zPostPtzLoadResponse = z.string();

export const PtzMoveBodySchema = z.object({
  direction: z.enum([
    "upleft",
    "up",
    "upright",
    "left",
    "home",
    "right",
    "downleft",
    "down",
    "downright",
    "stop",
  ]),
});

export const zPostPtzMoveHeaders = z.object({
  "x-camera-name": z.string().min(1).max(100),
});

/**
 * Successfully submitted to the camera
 */
export const zPostPtzMoveResponse = z.string();

export const PtzPanBodySchema = z.object({
  degrees: z.intersection(z.number().gte(-180), z.number().lte(180)),
});

export const zPostPtzPanHeaders = z.object({
  "x-camera-name": z.string().min(1).max(100),
});

/**
 * Successfully submitted to the camera
 */
export const zPostPtzPanResponse = z.string();

export const PtzTiltBodySchema = z.object({
  degrees: z.intersection(z.number().gte(-180), z.number().lte(180)),
});

export const zPostPtzTiltHeaders = z.object({
  "x-camera-name": z.string().min(1).max(100),
});

/**
 * Successfully submitted to the camera
 */
export const zPostPtzTiltResponse = z.string();

export const PtzZoomBodySchema = z.object({
  value: z.intersection(z.number().gte(1), z.number().lte(19999)),
});

export const zPostPtzZoomHeaders = z.object({
  "x-camera-name": z.string().min(1).max(100),
});

/**
 * Successfully submitted to the camera
 */
export const zPostPtzZoomResponse = z.string();

export const PtzAreazoomBodySchema = z.object({
  x: z.number(),
  y: z.number(),
  z: z.number().gte(1),
});

export const zPostPtzAreazoomHeaders = z.object({
  "x-camera-name": z.string().min(1).max(100),
});

/**
 * Successfully submitted to the camera
 */
export const zPostPtzAreazoomResponse = z.string();

export const PtzSpinBodySchema = z.object({
  pan: z.intersection(z.number().gte(-100), z.number().lte(100)),
  tilt: z.intersection(z.number().gte(-100), z.number().lte(100)),
  zoom: z.intersection(z.number().gte(-100), z.number().lte(100)),
});

export const zPostPtzSpinHeaders = z.object({
  "x-camera-name": z.string().min(1).max(100),
});

/**
 * Successfully submitted to the camera
 */
export const zPostPtzSpinResponse = z.string();

export const PtzRptzBodySchema = z.object({
  pan: z.intersection(z.number().gte(-360), z.number().lte(360)).optional(),
  tilt: z.intersection(z.number().gte(-360), z.number().lte(360)).optional(),
  zoom: z
    .intersection(z.number().gte(-19999), z.number().lte(19999))
    .optional(),
});

export const zPostPtzRptzHeaders = z.object({
  "x-camera-name": z.string().min(1).max(100),
});

/**
 * Successfully submitted to the camera
 */
export const zPostPtzRptzResponse = z.string();

export const PtzRpanBodySchema = z.object({
  degrees: z.intersection(z.number().gte(-360), z.number().lte(360)),
});

export const zPostPtzRpanHeaders = z.object({
  "x-camera-name": z.string().min(1).max(100),
});

/**
 * Successfully submitted to the camera
 */
export const zPostPtzRpanResponse = z.string();

export const PtzRtiltBodySchema = z.object({
  degrees: z.intersection(z.number().gte(-360), z.number().lte(360)),
});

export const zPostPtzRtiltHeaders = z.object({
  "x-camera-name": z.string().min(1).max(100),
});

/**
 * Successfully submitted to the camera
 */
export const zPostPtzRtiltResponse = z.string();

export const PtzRzoomBodySchema = z.object({
  value: z.intersection(z.number().gte(-19999), z.number().lte(19999)),
});

export const zPostPtzRzoomHeaders = z.object({
  "x-camera-name": z.string().min(1).max(100),
});

/**
 * Successfully submitted to the camera
 */
export const zPostPtzRzoomResponse = z.string();

export const IrBodySchema = z.object({
  light: z.string().regex(/^led\d$/),
  state: z.enum(["on", "off", "auto"]),
});

export const zPostIrHeaders = z.object({
  "x-camera-name": z.string().min(1).max(100),
});

/**
 * Successfully submitted to the camera
 */
export const zPostIrResponse = z.string();

export const IrFilterBodySchema = z.object({
  state: z.enum(["on", "off", "auto"]),
});

export const zPostIrFilterHeaders = z.object({
  "x-camera-name": z.string().min(1).max(100),
});

/**
 * Successfully submitted to the camera
 */
export const zPostIrFilterResponse = z.string();

export const IrLightBodySchema = z.object({
  light: z.string().regex(/^led\d$/),
  state: z.enum(["on", "off"]),
});

export const zPostIrLightHeaders = z.object({
  "x-camera-name": z.string().min(1).max(100),
});

/**
 * Successfully submitted to the camera
 */
export const zPostIrLightResponse = z.string();

export const zGetInfoPositionHeaders = z.object({
  "x-camera-name": z.string().min(1).max(100),
});

/**
 * Information about a camera
 */
export const zGetInfoPositionResponse = z.record(
  z.string(),
  z.union([z.number(), z.string()]),
);

export const zGetInfoSpeedHeaders = z.object({
  "x-camera-name": z.string().min(1).max(100),
});

/**
 * Speed of the camera
 */
export const zGetInfoSpeedResponse = z.record(
  z.string(),
  z.union([z.number(), z.string()]),
);

export const zGetInfoScreenshotHeaders = z.object({
  "x-camera-name": z.string().min(1).max(100),
});

export const zGetInfoScreenshotQuery = z.object({
  width: z.int().gt(0).lte(9007199254740991).optional(),
  height: z.int().gt(0).lte(9007199254740991).optional(),
});

/**
 * Base64 encoded image
 */
export const zGetInfoScreenshotResponse = z.string();

export const zGetInfoResolutionHeaders = z.object({
  "x-camera-name": z.string().min(1).max(100),
});

/**
 * Current resolution
 */
export const zGetInfoResolutionResponse = z.record(
  z.string(),
  z.union([z.number(), z.string()]),
);

export const ImagingFocusBodySchema = z.object({
  value: z.intersection(z.number().gte(1), z.number().lte(9999)),
});

export const zPostImagingFocusHeaders = z.object({
  "x-camera-name": z.string().min(1).max(100),
});

/**
 * Successfully submitted to the camera
 */
export const zPostImagingFocusResponse = z.string();

export const ImagingBrightnessBodySchema = z.object({
  value: z.intersection(z.number().gte(1), z.number().lte(9999)),
});

export const zPostImagingBrightnessHeaders = z.object({
  "x-camera-name": z.string().min(1).max(100),
});

/**
 * Successfully submitted to the camera
 */
export const zPostImagingBrightnessResponse = z.string();

export const ImagingIrisBodySchema = z.object({
  value: z.intersection(z.number().gte(1), z.number().lte(9999)),
});

export const zPostImagingIrisHeaders = z.object({
  "x-camera-name": z.string().min(1).max(100),
});

/**
 * Successfully submitted to the camera
 */
export const zPostImagingIrisResponse = z.string();

export const ImagingRfocusBodySchema = z.object({
  value: z.intersection(z.number().gte(-9999), z.number().lte(9999)),
});

export const zPostImagingRfocusHeaders = z.object({
  "x-camera-name": z.string().min(1).max(100),
});

/**
 * Successfully submitted to the camera
 */
export const zPostImagingRfocusResponse = z.string();

export const ImagingRbrightnessBodySchema = z.object({
  value: z.intersection(z.number().gte(-9999), z.number().lte(9999)),
});

export const zPostImagingRbrightnessHeaders = z.object({
  "x-camera-name": z.string().min(1).max(100),
});

/**
 * Successfully submitted to the camera
 */
export const zPostImagingRbrightnessResponse = z.string();

export const ImagingRirisBodySchema = z.object({
  value: z.intersection(z.number().gte(-9999), z.number().lte(9999)),
});

export const zPostImagingRirisHeaders = z.object({
  "x-camera-name": z.string().min(1).max(100),
});

/**
 * Successfully submitted to the camera
 */
export const zPostImagingRirisResponse = z.string();

export const ImagingAutofocusBodySchema = z.object({
  state: z.enum(["on", "off"]),
});

export const zPostImagingAutofocusHeaders = z.object({
  "x-camera-name": z.string().min(1).max(100),
});

/**
 * Successfully submitted to the camera
 */
export const zPostImagingAutofocusResponse = z.string();

export const ImagingAutoirisBodySchema = z.object({
  state: z.enum(["on", "off"]),
});

export const zPostImagingAutoirisHeaders = z.object({
  "x-camera-name": z.string().min(1).max(100),
});

/**
 * Successfully submitted to the camera
 */
export const zPostImagingAutoirisResponse = z.string();

export const ImagingCfocusBodySchema = z.object({
  value: z.intersection(z.number().gte(-100), z.number().lte(100)),
});

export const zPostImagingCfocusHeaders = z.object({
  "x-camera-name": z.string().min(1).max(100),
});

/**
 * Successfully submitted to the camera
 */
export const zPostImagingCfocusResponse = z.string();

export const ImagingCbrightnessBodySchema = z.object({
  value: z.intersection(z.number().gte(-100), z.number().lte(100)),
});

export const zPostImagingCbrightnessHeaders = z.object({
  "x-camera-name": z.string().min(1).max(100),
});

/**
 * Successfully submitted to the camera
 */
export const zPostImagingCbrightnessResponse = z.string();

export const ImagingCirisBodySchema = z.object({
  value: z.intersection(z.number().gte(-100), z.number().lte(100)),
});

export const zPostImagingCirisHeaders = z.object({
  "x-camera-name": z.string().min(1).max(100),
});

/**
 * Successfully submitted to the camera
 */
export const zPostImagingCirisResponse = z.string();

export const zGetSettingsQuickzoomHeaders = z.object({
  "x-camera-name": z.string().min(1).max(100),
});

/**
 * Parameter state
 */
export const zGetSettingsQuickzoomResponse = z.record(z.string(), z.unknown());

export const SettingsQuickzoomBodySchema = z.object({
  enabled: z.boolean(),
});

export const zPostSettingsQuickzoomHeaders = z.object({
  "x-camera-name": z.string().min(1).max(100),
});

/**
 * Parameter state
 */
export const zPostSettingsQuickzoomResponse = z.record(z.string(), z.unknown());

export const zGetSettingsSpotfocusHeaders = z.object({
  "x-camera-name": z.string().min(1).max(100),
});

/**
 * Parameter state
 */
export const zGetSettingsSpotfocusResponse = z.record(z.string(), z.unknown());

export const SettingsSpotfocusBodySchema = z.object({
  enabled: z.boolean(),
});

export const zPostSettingsSpotfocusHeaders = z.object({
  "x-camera-name": z.string().min(1).max(100),
});

/**
 * Parameter state
 */
export const zPostSettingsSpotfocusResponse = z.record(z.string(), z.unknown());

export const zGetSettingsSaturationHeaders = z.object({
  "x-camera-name": z.string().min(1).max(100),
});

/**
 * Parameter state
 */
export const zGetSettingsSaturationResponse = z.record(z.string(), z.unknown());

export const SettingsSaturationBodySchema = z.object({
  value: z.intersection(z.number().gte(0), z.number().lte(100)),
});

export const zPostSettingsSaturationHeaders = z.object({
  "x-camera-name": z.string().min(1).max(100),
});

/**
 * Parameter state
 */
export const zPostSettingsSaturationResponse = z.record(
  z.string(),
  z.unknown(),
);

export const zGetSettingsBrightnessHeaders = z.object({
  "x-camera-name": z.string().min(1).max(100),
});

/**
 * Parameter state
 */
export const zGetSettingsBrightnessResponse = z.record(z.string(), z.unknown());

export const SettingsBrightnessBodySchema = z.object({
  value: z.intersection(z.number().gte(0), z.number().lte(100)),
});

export const zPostSettingsBrightnessHeaders = z.object({
  "x-camera-name": z.string().min(1).max(100),
});

/**
 * Parameter state
 */
export const zPostSettingsBrightnessResponse = z.record(
  z.string(),
  z.unknown(),
);

export const zGetSettingsContrastHeaders = z.object({
  "x-camera-name": z.string().min(1).max(100),
});

/**
 * Parameter state
 */
export const zGetSettingsContrastResponse = z.record(z.string(), z.unknown());

export const SettingsContrastBodySchema = z.object({
  value: z.intersection(z.number().gte(0), z.number().lte(100)),
});

export const zPostSettingsContrastHeaders = z.object({
  "x-camera-name": z.string().min(1).max(100),
});

/**
 * Parameter state
 */
export const zPostSettingsContrastResponse = z.record(z.string(), z.unknown());

export const zGetSettingsSharpnessHeaders = z.object({
  "x-camera-name": z.string().min(1).max(100),
});

/**
 * Parameter state
 */
export const zGetSettingsSharpnessResponse = z.record(z.string(), z.unknown());

export const SettingsSharpnessBodySchema = z.object({
  value: z.intersection(z.number().gte(0), z.number().lte(100)),
});

export const zPostSettingsSharpnessHeaders = z.object({
  "x-camera-name": z.string().min(1).max(100),
});

/**
 * Parameter state
 */
export const zPostSettingsSharpnessResponse = z.record(z.string(), z.unknown());

export const zGetSettingsLocalcontrastHeaders = z.object({
  "x-camera-name": z.string().min(1).max(100),
});

/**
 * Parameter state
 */
export const zGetSettingsLocalcontrastResponse = z.record(
  z.string(),
  z.unknown(),
);

export const SettingsLocalcontrastBodySchema = z.object({
  value: z.intersection(z.number().gte(0), z.number().lte(100)),
});

export const zPostSettingsLocalcontrastHeaders = z.object({
  "x-camera-name": z.string().min(1).max(100),
});

/**
 * Parameter state
 */
export const zPostSettingsLocalcontrastResponse = z.record(
  z.string(),
  z.unknown(),
);

export const zGetSettingsTonemappingHeaders = z.object({
  "x-camera-name": z.string().min(1).max(100),
});

/**
 * Parameter state
 */
export const zGetSettingsTonemappingResponse = z.record(
  z.string(),
  z.unknown(),
);

export const SettingsTonemappingBodySchema = z.object({
  value: z.intersection(z.number().gte(0), z.number().lte(100)),
});

export const zPostSettingsTonemappingHeaders = z.object({
  "x-camera-name": z.string().min(1).max(100),
});

/**
 * Parameter state
 */
export const zPostSettingsTonemappingResponse = z.record(
  z.string(),
  z.unknown(),
);

export const zGetSettingsProportionalspeedHeaders = z.object({
  "x-camera-name": z.string().min(1).max(100),
});

/**
 * Parameter state
 */
export const zGetSettingsProportionalspeedResponse = z.record(
  z.string(),
  z.unknown(),
);

export const SettingsProportionalspeedBodySchema = z.object({
  value: z.intersection(z.number().gte(0), z.number().lte(1000)),
});

export const zPostSettingsProportionalspeedHeaders = z.object({
  "x-camera-name": z.string().min(1).max(100),
});

/**
 * Parameter state
 */
export const zPostSettingsProportionalspeedResponse = z.record(
  z.string(),
  z.unknown(),
);

export const zGetSettingsSpeedHeaders = z.object({
  "x-camera-name": z.string().min(1).max(100),
});

/**
 * Speed of the camera
 */
export const zGetSettingsSpeedResponse = z.record(
  z.string(),
  z.union([z.number(), z.string()]),
);

export const SettingsSpeedBodySchema = z.object({
  value: z.intersection(z.number().gte(1), z.number().lte(100)),
});

export const zPostSettingsSpeedHeaders = z.object({
  "x-camera-name": z.string().min(1).max(100),
});

/**
 * Updated camera speed
 */
export const zPostSettingsSpeedResponse = z.record(
  z.string(),
  z.union([z.number(), z.string()]),
);

export const zGetConfigCapabilitiesByCameraPath = z.object({
  camera: z.string().min(1),
});

/**
 * Camera capabilities
 */
export const zGetConfigCapabilitiesByCameraResponse = z.object({
  camera: z.string(),
  capabilities: z.array(z.string()),
});

export const zGetConfigSpecsByCameraPath = z.object({
  camera: z.string().min(1),
});

/**
 * Camera specs
 */
export const zGetConfigSpecsByCameraResponse = z.object({
  camera: z.string(),
  specs: z.record(z.string(), z.unknown()),
});
