name: Sync from Public

on:
  schedule:
    - cron: "0 * * * *" # hourly
  workflow_dispatch:

permissions: {}

jobs:
  sync:
    if: github.repository == 'alveusgg/alveusgg-private'
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout private repo
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: true
          ref: ${{ github.ref }}
          token: ${{ secrets.GH_SYNC_TOKEN }}

      - name: Fetch public repo and push
        env:
          BRANCH: ${{ github.ref_name }}
        run: |
          git remote add upstream https://github.com/alveusgg/alveusgg.git
          git fetch upstream "$BRANCH"
          git push origin "upstream/$BRANCH:$BRANCH"
