name: Update Chatbot

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
      - "preview"
    paths:
      - "apps/chatbot/**"
      - "package.json"
      - "pnpm-lock.yaml"
      - "pnpm-workspace.yaml"
      - ".github/workflows/update-chatbot.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  COMPOSE_PROJECT_NAME: ${{ vars.CHATBOT_COMPOSE_PROJECT_NAME }}
  CHATBOT_PATH: ${{ vars.CHATBOT_PATH }}
  REF_NAME: ${{ github.ref_name }}
  REF_SHA: ${{ github.sha }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
  packages: read

jobs:
  deploy:
    name: Deploy (${{ (github.ref == 'refs/heads/main' && 'production') || 'preview' }})
    environment: ${{ (github.ref == 'refs/heads/main' && 'production') || 'preview' }}
    runs-on: ubuntu-latest
    if: github.repository == 'alveusgg/alveusgg'
    timeout-minutes: 10
    steps:
      - name: Update Chatbot via SSH
        uses: appleboy/ssh-action@0ff4204d59e8e51228ff73bce53f80d53301dee2 # v1.2.5
        with:
          envs: COMPOSE_PROJECT_NAME,CHATBOT_PATH,REF_NAME,REF_SHA,GITHUB_TOKEN
          host: ${{ secrets.CHATBOT_HOST }}
          username: ${{ secrets.CHATBOT_USERNAME }}
          key: ${{ secrets.CHATBOT_KEY }}
          port: ${{ secrets.CHATBOT_PORT }}
          passphrase: ${{ secrets.CHATBOT_PASSPHRASE }}
          script: |
            set -e
            cd $CHATBOT_PATH
            git fetch origin $REF_NAME && git reset --hard origin/$REF_NAME
            cd apps/chatbot
            CHATBOT_REF_SHA=$REF_SHA docker compose up --build --detach
            docker system prune --force
